name: Testing

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  tests:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install selenium==3.141.0
          pip3 install html-testRunner==1.2.1
          pip install Jinja2==3.0.1
          pip install MarkupSafe==2.0.1
          pip install urllib3==1.26.5
          pip install numpy
          
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |       
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          chmod +x Twitter-Testing-master/chromedriver.exe
          chmod +x ./Twitter-Testing-master/InstallChrome.sh
          ./Twitter-Testing-master/InstallChrome.sh
          #CI=true python3 Twitter-Testing-master/main.py 
          CI=true python3 Twitter-Testing-master/Account_info.py
          CI=true python3 Twitter-Testing-master/change_pass.py
          CI=true python3 Twitter-Testing-master/Edit_Profile.py
          CI=true python3 Twitter-Testing-master/Home_Page.py
          CI=true python3 Twitter-Testing-master/your_Account.py
          CI=true python3 Twitter-Testing-master/Side_bar.py 
          CI=true python3 Twitter-Testing-master/Settings_Privacy.py 
